          </tbody>
        </table>
      </div>

      <h2>Vulnerabilities</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm order-column" id="vulnerabilities">
          <thead>
            <tr>
              <th>Vulnerability</th>
              <th>Resource</th>
              <th>Fix Version</th>
              <th>Aqua Score</th>
              <th>Aqua Severity</th>
              <th>Publish Date</th>
              <th>Modification Date</th>
            </tr>
          </thead>
          <tbody>