			<div class="image-overview box mt20">
				<h4 class="title">Image Overview</h4>
				<ul class="vuln-nums clearfix">
					<li class="vuln">
						<span class="square darkred"></span>
						<span>&&CRITICAL&& Critical</span>
					</li>
					<li class="vuln">
						<span class="square red"></span>
						<span>&&HIGH&& High</span>
					</li>
					<li class="vuln">
						<span class="square orange"></span>
						<span>&&MEDIUM&& Medium</span>
					</li>
					<li class="vuln">
						<span class="square yellow"></span>
						<span>&&LOW&& Low</span>
					</li>
					<li class="vuln">
						<span class="square green"></span>
						<span>&&NEGLIGIBLE&& Negligible</span>
					</li>
				</ul>
			</div>			
			
			<div class="assurance-checks box mt20">
				<h4 class="title">Image Assurance</h4>
				<ul>					
