				</ul>
			</div>	
		</div>
		

		<input type="radio" class="tab" name="tabs" id="tab2">
		<label for="tab2" class="label">Vulnerabilities</label>
		
		<div class="panel tab2">
			<input type="checkbox" id="group" class="group-by" checked="false">
			<label for="group" class="label">Group by resource</label>
            <div class="wrapper">
				
				<div class="resources mt20">
					<div class="headers flex mb10">
						<span class="flex1">Resource</span>
						<span class="flex1">Type</span>
						<span class="flex1">Version</span>
						<span class="flex1">Format</span>
						<span class="flex1">Arch</span>
					</div>