name: Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get base image if Dockerfile exists
        run: |
          if [ -f Dockerfile ]; then
            BASE_IMAGE=$(head -1 Dockerfile | awk '{split($0,a," "); print a[2]}')
            echo $BASE_IMAGE
          else
            echo No Dockerfile found
          fi
